name: extract a zip file
on:
  push:
    paths:
    - '**.zip'
  workflow_dispatch:
jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: unzipper
        run: |
          unzip *.zip
